#!/bin/sh /etc/rc.common
#
# Author: Zhifeng Gu <guzhifeng1979@hotmail.com>
# Date: 2012/03
# License: GPL

START=40
STOP=90

run_multimac() {
    local cfg="$1"
    local count

    config_get count "$cfg" count
    if [ -n "$count" ]; then
        multimac $count > /dev/null
    fi
}

start() {
    . /etc/functions.sh

    config_load mmac
    config_foreach run_multimac multimac
}

stop() {
    killall multimac
}

restart() {
    stop
    start
}
